// Built-in prompt presets. task: "edit" (instruction for an existing image) or "generate" (text to image).
export const BUILTIN_PROMPTS = [
  // ---- edit
  { id: "e-remove", task: "edit", title: "Remove object or person",
    prompt: "Remove the masked object and fill the area with the surrounding background, matching texture, lighting and perspective. Keep everything else unchanged." },
  { id: "e-beach", task: "edit", title: "Beach at sunset background",
    prompt: "Replace the background with a quiet beach at sunset, warm orange light and soft waves. Keep the subject unchanged." },
  { id: "e-night", task: "edit", title: "Day to night",
    prompt: "Change the scene from day to night: dark blue sky, glowing street lights and windows, soft moonlight. Keep all objects in place." },
  { id: "e-winter", task: "edit", title: "Winter with snow",
    prompt: "Change the season to winter: snow on the ground and on the roofs, bare trees, cold light. Keep the composition unchanged." },
  { id: "e-clothes", task: "edit", title: "Change clothing colour",
    prompt: "Change the colour of the clothing to deep red. Keep the fabric texture, folds and everything else unchanged." },
  { id: "e-oil", task: "edit", title: "Oil painting look",
    prompt: "Turn the image into an oil painting with visible brush strokes and rich colours. Keep the composition and the subject recognisable." },
  { id: "e-restore", task: "edit", title: "Restore an old photo",
    prompt: "Restore this old photo: remove scratches, dust and stains, repair faded areas, and gently improve contrast and sharpness. Keep the original look." },
  { id: "e-studio", task: "edit", title: "Soft studio lighting",
    prompt: "Add soft studio lighting with gentle shadows and a subtle rim light. Keep the subject, pose and background unchanged." },
  // ---- generate
  { id: "g-sticker", task: "generate", title: "Transparent sticker",
    prompt: "This is an RGBA image with transparency. A cute cartoon dragon sticker. The image has alpha channel and the background is transparent." },
  { id: "g-product", task: "generate", title: "Product photo on marble",
    prompt: "A product photo of a glass perfume bottle on a white marble surface, soft window light, subtle reflections, shallow depth of field, clean minimal composition." },
  { id: "g-portrait", task: "generate", title: "Cinematic portrait",
    prompt: "A cinematic portrait of an elderly fisherman at golden hour, weathered face, warm side light, shallow depth of field, film grain, 85mm lens." },
  { id: "g-room", task: "generate", title: "Isometric cozy room",
    prompt: "An isometric view of a cozy reading room with a warm lamp, bookshelves, a green armchair and plants, soft colours, detailed miniature diorama style." },
  { id: "g-watercolor", task: "generate", title: "Watercolor landscape",
    prompt: "A watercolor landscape of rolling hills and a small village at dawn, soft washes of colour, visible paper texture, gentle mist." },
  { id: "g-logo", task: "generate", title: "Minimalist logo",
    prompt: "A minimalist logo of a mountain and a sun, flat vector style, two colours, clean shapes, centred on a plain white background." },
  { id: "g-macro", task: "generate", title: "Macro nature photo",
    prompt: "A macro photo of a dewdrop on a spider web at sunrise, sharp focus, creamy bokeh background, fine detail." },
  { id: "g-poster", task: "generate", title: "Retro poster",
    prompt: "A retro travel poster of a lighthouse on a rocky coast, bold flat colours, 1960s illustration style, large title area at the top." },
];
